# Generated by Django 4.1.2 on 2022-11-10 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0011_rename_customer_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='file_name',
        ),
    ]
